# NumPy ndarray : 다차원 배열 객체
NumPy의 핵심 기능 중 하나는 N차원의 배열 객체 또는 ndarray이다.

In [3]:
import numpy as np

In [4]:
data = np.random.randn(2,3)

In [6]:
data

array([[-0.11017114, -0.34128983, -1.12976038],
       [-0.46142861, -1.73459694,  1.4914381 ]])

In [7]:
data * 10

array([[ -1.10171143,  -3.41289826, -11.29760378],
       [ -4.61428607, -17.34596937,  14.91438101]])

In [8]:
data + data

array([[-0.22034229, -0.68257965, -2.25952076],
       [-0.92285721, -3.46919387,  2.9828762 ]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
data1 = [6,7.5,8,0,1]

In [12]:
arr1 = np.array(data1)

In [13]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int64')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
arr = np.arange(10)

In [24]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[5]

5

In [26]:
arr[5:8]

array([5, 6, 7])

In [27]:
arr[5:8]=12

In [28]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [29]:
arr_slice = arr[5:8]

In [30]:
arr_slice[1] = 12345

In [31]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [33]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
arr2d[2]

array([7, 8, 9])

In [35]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [36]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [40]:
arr3d[1,0]

array([7, 8, 9])

In [41]:
arr3d[0,0]

array([1, 2, 3])

In [42]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [46]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [47]:
arr[:7]

array([    0,     1,     2,     3,     4,    12, 12345])

In [48]:
arr[1:]

array([    1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [49]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr2d[:1,1:]

array([[2, 3]])

In [51]:
arr = np.arange(10)

In [52]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [53]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [54]:
x = np.random.randn(8)

In [55]:
y = np.random.randn(8)

In [56]:
x

array([-0.39611877, -1.19098609,  0.59991179,  0.4583601 , -0.22991626,
       -0.71900492,  0.16051088, -2.3353192 ])

In [57]:
y

array([ 2.35863719, -0.14455794, -1.55348073,  0.28934273, -0.15225081,
        0.5914133 , -0.07000785,  2.03896188])